### ISSUE TITLE
Errors in tests that got changed to plain phpunit

### ISSUE THREAD

**Issue by BenjaminQuandt** [DMKEBUSINESSGMBH/typo3-mksanitizedparameters#6]
I found some errors in the tests that i could not fix:

tx_mksanitizedparameters_hooks_PreprocessTypo3RequestsTest:
- TYPO3\CMS\Core\Cache\Exception\NoSuchCacheException: A cache with identifier "assets" does not exist.

tx_mksanitizedparametersTest:

- Warning: Uncaught require(typo3-mksanitizedparameters/.Build/Web/typo3conf/LocalConfiguration.php): failed to open stream: No such file or directory

**Comment by rengaw83** [comment]
Both problems have been corrected in v10.0.0.
